package br.ufrj.macae.tic.persistence.entity;
// Generated 26/05/2017 12:44:14 by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Disposition generated by hbm2java
 */
@Entity
@Table(name = "disposition", catalog = "peld")
public class Disposition implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4492583739974647513L;
	
	private long id;
	private String disposition;
	
	private List<Occurrence> occurrences;

	public Disposition() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "disposition", length = 60)
	public String getDisposition() {
		return this.disposition;
	}

	public void setDisposition(String disposition) {
		this.disposition = disposition;
	}
	
	/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "disposition")
	public List<Occurrence> getOccurrences() {
		return this.occurrences;
	}

	public void setOccurrences(List<Occurrence> occurrences) {
		this.occurrences = occurrences;
	}
	*/

}
