package br.ufrj.macae.tic.persistence.entity;
// Generated 26/05/2017 12:44:14 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estableshiment generated by hbm2java
 */
@Entity
@Table(name = "estableshiment", catalog = "peld")
public class Estableshiment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3706300255365290427L;
	private long id;
	private String estableshiment;
	private List<Occurrence> occurrences;

	public Estableshiment() {
	}

	public Estableshiment(String estableshiment) {
		this.estableshiment = estableshiment;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "estableshiment", nullable = false, length = 60)
	public String getEstableshiment() {
		return this.estableshiment;
	}

	public void setEstableshiment(String estableshiment) {
		this.estableshiment = estableshiment;
	}


	/*
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estableshiment")
	public List<Occurrence> getOccurrences() {
		return this.occurrences;
	}

	public void setOccurrences(List<Occurrence> occurrences) {
		this.occurrences = occurrences;
	}
	
	*/

}
