package br.ufrj.macae.tic.persistence.entity;
// Generated 26/05/2017 12:44:14 by Hibernate Tools 5.2.1.Final

import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Municipality generated by hbm2java
 */
@Entity
@Table(name = "municipality", catalog = "peld")
public class Municipality implements java.io.Serializable {

	private long id;
	private String municipality;
	private List<WaterBody> waterBodyList;

	

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "municipality", nullable = false, length = 120)
	public String getMunicipality() {
		return this.municipality;
	}

	public void setMunicipality(String municipality) {
		this.municipality = municipality;
	}

	/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "municipality")
	public List<Location> getLocations() {
		return this.locations;
	}

	public void setLocations(List<Location> locations) {
		this.locations = locations;
	} */
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "waterBody")
	public List<WaterBody> getwaterBodyList() {
		return this.waterBodyList;
	}

	public void setwaterBodyList(List<WaterBody> waterBodyList) {
		this.waterBodyList = waterBodyList;
	}

}
