package br.ufrj.macae.tic.persistence.entity;
// Generated 26/05/2017 12:44:14 by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Organism generated by hbm2java
 */
@Entity
@Table(name = "organism", catalog = "peld")
public class Organism implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6795490634110306130L;
	private long id;
	private String sex;
	private String organismNumber;
	
	private Occurrence occurrence;
	
	private List<EmbryonicPhase> embryonicPhaseList;
	
	private List<Measurement> measurementList;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "occurrenceId")
	public Occurrence getOccurrence() {
		return occurrence;
	}
	
	public void setOccurrence(Occurrence occurrence) {
		this.occurrence = occurrence;
	}
	

	@Column(name = "sex", length = 45)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "organismNumber", length = 45)
	public String getOrganismNumber() {
		return this.organismNumber;
	}

	public void setOrganismNumber(String organismNumber) {
		this.organismNumber = organismNumber;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organism")
	public List<EmbryonicPhase> getEmbryonicPhaseList() {
		return embryonicPhaseList;
	}


	public void setEmbryonicPhaseList(List<EmbryonicPhase> embryonicPhaseList) {
		this.embryonicPhaseList = embryonicPhaseList;
	}
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organism")
	public List<Measurement> getMeasurement() {
		return measurementList;
	}


	public void setMeasurement(List<Measurement> measurementList) {
		this.measurementList = measurementList;
	}
}
