package br.ufrj.macae.tic.persistence.entity;
// Generated 26/05/2017 12:44:14 by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;import com.sun.faces.application.ProjectStageJndiFactory;

/**
 * Organization generated by hbm2java
 */
@Entity
@Table(name = "organization", catalog = "peld")
public class Organization implements java.io.Serializable {

	private long id;
	private String organizationName;
	
	//private List projectsForExecuteInstituitionId;
	//private List projectsForCollaboratingInstituitionId;
	//private List projectsForFinancialInstituitionId;
	
	private List<Person> persons;

	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "organizationName", nullable = false, length = 120)
	public String getOrganizationName() {
		return this.organizationName;
	}

	public void setOrganizationName(String organizationName) {
		this.organizationName = organizationName;
	}

	/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organizationByExecuteInstituitionId")
	public List getProjectsForExecuteInstituitionId() {
		return this.projectsForExecuteInstituitionId;
	}

	public void setProjectsForExecuteInstituitionId(List projectsForExecuteInstituitionId) {
		this.projectsForExecuteInstituitionId = projectsForExecuteInstituitionId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organizationByCollaboratingInstituitionId")
	public List getProjectsForCollaboratingInstituitionId() {
		return this.projectsForCollaboratingInstituitionId;
	}

	public void setProjectsForCollaboratingInstituitionId(List projectsForCollaboratingInstituitionId) {
		this.projectsForCollaboratingInstituitionId = projectsForCollaboratingInstituitionId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organizationByFinancialInstituitionId")
	public List<Integer> getProjectsForFinancialInstituitionId() {
		return this.projectsForFinancialInstituitionId;
	}

	public void setProjectsForFinancialInstituitionId(List projectsForFinancialInstituitionId) {
		this.projectsForFinancialInstituitionId = projectsForFinancialInstituitionId;
	}
 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organization")
	public List<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(List<Person> persons) {
		this.persons = persons;
	}

}
