package br.ufrj.macae.tic.persistence.entity;
// Generated 26/05/2017 12:44:14 by Hibernate Tools 5.2.1.Final

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "organismQuantityType", catalog = "peld")
public class OrganismQuantityType implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = -2888104418656465029L;

	private int id;
		
	private String organismQuantityType;
	
	private List<Occurrence> occurrences;
	

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	

	@Column(name = "organismQuantityType")
	public String getOrganismQuantityType() {
		return this.organismQuantityType;
	}

	public void setOrganismQuantityType(String organismQuantityType) {
		this.organismQuantityType = organismQuantityType;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "organismQuantityTypeId")
	public List<Occurrence> getOccurrences() {
		return this.occurrences;
	}

	public void setOccurrences(List<Occurrence> occurrences) {
		this.occurrences = occurrences;
	}

}
