package br.ufrj.macae.tic.persistence.entity;
// Generated 26/05/2017 12:44:14 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ResearchArea generated by hbm2java
 */
@Entity
@Table(name = "research area", catalog = "peld")
public class ResearchArea implements java.io.Serializable {

	private long id;
	private String researchAreaName;
	private List<ResearchSubarea> researchSubareas;


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "researchAreaName", nullable = false, length = 120)
	public String getResearchAreaName() {
		return this.researchAreaName;
	}

	public void setResearchAreaName(String researchAreaName) {
		this.researchAreaName = researchAreaName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "researchArea")
	public List<ResearchSubarea> getResearchSubareas() {
		return this.researchSubareas;
	}

	public void setResearchSubareas(List<ResearchSubarea> researchSubareas) {
		this.researchSubareas = researchSubareas;
	}

}
