package br.ufrj.macae.tic.persistence.entity;
// Generated 26/05/2017 12:44:14 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ResearchSubarea generated by hbm2java
 */
@Entity
@Table(name = "research subarea", catalog = "peld")
public class ResearchSubarea implements java.io.Serializable {

	private long id;
	private ResearchArea researchArea;
	private String researchSubAreaName;
	private List<SubprojectSubarea> subprojectSubareas;

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "researchAreaId", nullable = false)
	public ResearchArea getResearchArea() {
		return this.researchArea;
	}

	public void setResearchArea(ResearchArea researchArea) {
		this.researchArea = researchArea;
	}

	@Column(name = "researchSubAreaName", nullable = false, length = 120)
	public String getResearchSubAreaName() {
		return this.researchSubAreaName;
	}

	public void setResearchSubAreaName(String researchSubAreaName) {
		this.researchSubAreaName = researchSubAreaName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "researchSubarea")
	public List<SubprojectSubarea> getSubprojectSubareas() {
		return this.subprojectSubareas;
	}

	public void setSubprojectSubareas(List<SubprojectSubarea> subprojectSubareas) {
		this.subprojectSubareas = subprojectSubareas;
	}

}
