package br.ufrj.macae.tic.persistence.entity;
// Generated 26/05/2017 12:44:14 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SubprojectSubarea generated by hbm2java
 */
@Entity
@Table(name = "subproject_subarea", catalog = "peld")
public class SubprojectSubarea implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5279494073484567617L;
	private long id;
	private ResearchSubarea researchSubarea;
	private Subproject subproject;

	public SubprojectSubarea() {
	}

	public SubprojectSubarea(ResearchSubarea researchSubarea, Subproject subproject) {
		this.researchSubarea = researchSubarea;
		this.subproject = subproject;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "researchSubAreaId", nullable = false)
	public ResearchSubarea getResearchSubarea() {
		return this.researchSubarea;
	}

	public void setResearchSubarea(ResearchSubarea researchSubarea) {
		this.researchSubarea = researchSubarea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subprojectId", nullable = false)
	public Subproject getSubproject() {
		return this.subproject;
	}

	public void setSubproject(Subproject subproject) {
		this.subproject = subproject;
	}

}
