package br.ufrj.macae.tic.persistence.entity;
// Generated 26/05/2017 12:44:14 by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subproject generated by hbm2java
 */
@Entity
@Table(name = "subproject", catalog = "peld")
public class Subproject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1278420683694373691L;
	
	private long id;
	private String subprojectTitle;
	
	private long subprojectCoordinatorId;//criador
	private long projectId;
	
	@Column
	private String metadataLanguage;
	
	
	private long contactId;
	
	private long metadataProviderId;
	
	@Column
	private String subProjectDescription;
	
	@Column
	private String keywords;
	
	@Column
	private String licence;
	
	@Column
	private String geographicalDescription;
	
	@Column
	private float west;
	
	@Column
	private float east;
	
	@Column
	private float south;
	
	@Column
	private float north;
		
	@Column
	private Date inicialDateTemporal;
	
	@Column
	private Date endDateTemporal;
	
	@Column
	private String studyExtendy;
	
	@Column
	private String sampleDescription;
	
	@Column
	private String stepDescription;
	
	@Column
	private String dataLanguage;
	
	@Column
	private String sigla;
	
	private List<SubprojectSubarea> subprojectSubareas;
	private List<Event> events;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "subprojectTitle", nullable = false)
	public String getSubprojectTitle() {
		return this.subprojectTitle;
	}

	public void setSubprojectTitle(String subprojectTitle) {
		this.subprojectTitle = subprojectTitle;
	}

	@Column(name = "subprojectCoordinatorId", nullable = false)
	public long getSubprojectCoordinatorId() {
		return this.subprojectCoordinatorId;
	}

	public void setSubprojectCoordinatorId(long subprojectCoordinatorId) {
		this.subprojectCoordinatorId = subprojectCoordinatorId;
	}

	@Column(name = "projectId", nullable = false)
	public long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(long projectId) {
		this.projectId = projectId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subproject")
	public List<SubprojectSubarea> getSubprojectSubareas() {
		return this.subprojectSubareas;
	}

	public void setSubprojectSubareas(List<SubprojectSubarea> subprojectSubareas) {
		this.subprojectSubareas = subprojectSubareas;
	}	
	
	public String getMetadataLanguage() {
		return metadataLanguage;
	}

	public void setMetadataLanguage(String metadataLanguage) {
		this.metadataLanguage = metadataLanguage;
	}

	@Column(name="contact", nullable = false)
	public long getContactId() {
		return contactId;
	}

	public void setContactId(long contactId) {
		this.contactId = contactId;
	}

	@Column(name="metadataProvider", nullable = false)
	public long getMetadataProviderId() {
		return metadataProviderId;
	}

	public void setMetadataProviderId(long metadataProviderId) {
		this.metadataProviderId = metadataProviderId;
	}

	public String getSubProjectDescription() {
		return subProjectDescription;
	}

	public void setSubProjectDescription(String subProjectDescription) {
		this.subProjectDescription = subProjectDescription;
	}

	public String getKeywords() {
		return keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}


	public String getLicence() {
		return licence;
	}

	public void setLicence(String licence) {
		this.licence = licence;
	}

	public String getGeographicalDescription() {
		return geographicalDescription;
	}

	public void setGeographicalDescription(String geographicalDescription) {
		this.geographicalDescription = geographicalDescription;
	}

	public float getWest() {
		return west;
	}

	public void setWest(float west) {
		this.west = west;
	}

	public float getEast() {
		return east;
	}

	public void setEast(float east) {
		this.east = east;
	}

	public float getSouth() {
		return south;
	}

	public void setSouth(float south) {
		this.south = south;
	}

	public float getNorth() {
		return north;
	}

	public void setNorth(float north) {
		this.north = north;
	}


	public Date getInicialDateTemporal() {
		return inicialDateTemporal;
	}

	public void setInicialDateTemporal(Date inicialDateTemporal) {
		this.inicialDateTemporal = inicialDateTemporal;
	}

	public Date getEndDateTemporal() {
		return endDateTemporal;
	}

	public void setEndDateTemporal(Date endDateTemporal) {
		this.endDateTemporal = endDateTemporal;
	}

	public String getStudyExtendy() {
		return studyExtendy;
	}

	public void setStudyExtendy(String studyExtendy) {
		this.studyExtendy = studyExtendy;
	}

	public String getSampleDescription() {
		return sampleDescription;
	}

	public void setSampleDescription(String sampleDescription) {
		this.sampleDescription = sampleDescription;
	}

	public String getStepDescription() {
		return stepDescription;
	}

	public void setStepDescription(String stepDescription) {
		this.stepDescription = stepDescription;
	}
	
	public String getDataLanguage() {
		return dataLanguage;
	}

	public void setDataLanguage(String dataLanguage) {
		this.dataLanguage = dataLanguage;
	}
	
	public String getSigla() {
		return sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subproject")
	public List<Event> getEvents() {
		return this.events;
	}

	public void setEvents(List<Event> events) {
		this.events = events;
	}
}
