package br.ufrj.macae.tic.persistence.entity;
// Generated 26/05/2017 12:44:14 by Hibernate Tools 5.2.1.Final

import java.util.List;

import javax.inject.Inject;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "waterBody", catalog = "peld")
public class WaterBody implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5845238920610750943L;

	private int id;
		
	private String waterBody;
	private Double decimalLongitude;
	private Double decimalLatitude;
	
	
	@Inject
	private Habitat habitat;
	
	@Inject
	private County county;
	
	@Inject
	private Municipality municipality; 
	
	private List<Event> events;	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "habitatId")
	public Habitat getHabitat() {
		return this.habitat;
	}

	public void setHabitat(Habitat habitat) {
		this.habitat = habitat;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "countyId")
	public County getCounty() {
		return this.county;
	}

	public void setCounty(County county) {
		this.county = county;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "municipalityId")
	public Municipality getMunicipality() {
		return this.municipality;
	}

	public void setMunicipality(Municipality municipality) {
		this.municipality = municipality;
	}	


	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	

	@Column(name = "waterBody")
	public String getWaterBody() {
		return this.waterBody;
	}

	public void setWaterBody(String waterBody) {
		this.waterBody = waterBody;
	}
		
	public Double getDecimalLongitude() {
		return decimalLongitude;
	}

	public void setDecimalLongitude(Double decimalLongitude) {
		this.decimalLongitude = decimalLongitude;
	}
	

	public Double getDecimalLatitude() {
		return decimalLatitude;
	}

	public void setDecimalLatitude(Double decimalLatitude) {
		this.decimalLatitude = decimalLatitude;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "waterBody")
	public List<Event> getEvents() {
		return this.events;
	}

	public void setEvents(List<Event> events) {
		this.events = events;
	}
	
	

}
